# Generated by Django 4.2.5 on 2023-09-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OdooRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.PositiveIntegerField()),
                ("odoo_model", models.CharField(max_length=255)),
                ("django_id", models.CharField(max_length=255)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_records",
                        to="df_odoo.company",
                    ),
                ),
                (
                    "django_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OdooRecordImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_field", models.CharField(max_length=255)),
                ("django_field", models.CharField(max_length=255)),
                ("image_hash", models.CharField(max_length=255)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="df_odoo.odoorecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OdooConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_connection",
                        to="df_odoo.company",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="odoorecord",
            constraint=models.UniqueConstraint(
                fields=("company", "odoo_model", "odoo_id", "django_model"),
                name="unique_odoo_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="odoorecord",
            constraint=models.UniqueConstraint(
                fields=("django_model", "django_id"), name="unique_django_record"
            ),
        ),
    ]
